#!/usr/bin/env python3
"""Verify, publish, smoke-test, and record a container release (#555)."""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import re
import shlex
import socket
import subprocess
import sys
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlsplit
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from samuel.build_info import product_version_from_tag  # noqa: E402
from tools.release_gate import run_gate  # noqa: E402
from tools.update_container_locks import (  # noqa: E402
    BUILD_LOCK_PATH,
    POLICY_PATH,
    RUNTIME_LOCK_PATH,
    UV_VERSION,
    lock_inputs,
    lock_source_digest,
)

_DIGEST = re.compile(r"sha256:[0-9a-f]{64}\Z")
_FULL_REVISION = re.compile(r"(?:[0-9a-f]{40}|[0-9a-f]{64})\Z")
_IMAGE_REPOSITORY = re.compile(r"(?:[a-z0-9.-]+(?::[0-9]+)?/)?[a-z0-9]+(?:[._/-][a-z0-9]+)*\Z")
_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\]+)(?:\s*\\)?$", re.MULTILINE)
_DIRECT_NAME = re.compile(r"^([A-Za-z0-9_.-]+)")
_SAFE_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}\Z")
PUBLISHER_TOKEN_ENV = "SAMUEL_OCI_PUBLISHER_TOKEN"
RUNTIME_SCM_TOKEN_ENV = "SCM_TOKEN"


class ContainerReleaseError(RuntimeError):
    """Container input, image, smoke evidence, or manifest is inconsistent."""


def _sha256_path(path: Path) -> str:
    return f"sha256:{hashlib.sha256(path.read_bytes()).hexdigest()}"


def _sha256_json(value: Any) -> str:
    canonical = json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return f"sha256:{hashlib.sha256(canonical.encode('utf-8')).hexdigest()}"


def _canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def _direct_names(requirements: list[str]) -> set[str]:
    names: set[str] = set()
    for requirement in requirements:
        match = _DIRECT_NAME.match(requirement)
        if match is None:
            raise ContainerReleaseError(f"cannot read requirement name: {requirement!r}")
        names.add(_canonical_name(match.group(1)))
    return names


def _verify_lock(path: Path, required: set[str]) -> dict[str, str]:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ContainerReleaseError(f"cannot read {path}: {exc}") from exc
    matches = list(_PIN.finditer(content))
    if not matches:
        raise ContainerReleaseError(f"{path.name} contains no exact package pins")

    pins: dict[str, str] = {}
    for index, match in enumerate(matches):
        name = _canonical_name(match.group(1))
        if name in pins:
            raise ContainerReleaseError(f"{path.name} pins {name!r} more than once")
        pins[name] = match.group(2)
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        block = content[match.start() : end]
        if "--hash=sha256:" not in block:
            raise ContainerReleaseError(f"{path.name} pin {name!r} has no SHA-256 hash")

    missing = sorted(required - pins.keys())
    if missing:
        raise ContainerReleaseError(f"{path.name} misses direct requirements: {', '.join(missing)}")
    return pins


def load_policy(root: Path = ROOT) -> dict[str, Any]:
    path = root / POLICY_PATH
    try:
        policy = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ContainerReleaseError(f"cannot read {POLICY_PATH}: {exc}") from exc
    if not isinstance(policy, dict) or policy.get("schema_version") != 1:
        raise ContainerReleaseError("container lock policy schema must be 1")
    return policy


def verify_container_contract(root: Path = ROOT) -> dict[str, Any]:
    """Check locks, declared inputs, Dockerfile, Compose, and context offline."""

    policy = load_policy(root)
    contract = policy.get("lock_contract")
    base = policy.get("base_image")
    if not isinstance(contract, dict) or not isinstance(base, dict):
        raise ContainerReleaseError("container lock policy lacks contract or base image")
    if contract.get("generator") != f"uv=={UV_VERSION}":
        raise ContainerReleaseError(f"container locks must be generated by uv {UV_VERSION}")
    exclude_newer = contract.get("exclude_newer")
    if not isinstance(exclude_newer, str) or not re.fullmatch(
        r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", exclude_newer
    ):
        raise ContainerReleaseError("container lock cutoff must be an explicit UTC timestamp")

    inputs = lock_inputs(root)
    for field, expected in inputs.items():
        if contract.get(field) != expected:
            raise ContainerReleaseError(f"lock policy field {field!r} is stale")
    expected_source_digest = lock_source_digest(inputs)
    if contract.get("source_digest") != expected_source_digest:
        raise ContainerReleaseError(
            f"lock input digest is stale; expected {expected_source_digest}"
        )

    runtime = contract.get("runtime_lock")
    build = contract.get("build_lock")
    if not isinstance(runtime, dict) or not isinstance(build, dict):
        raise ContainerReleaseError("runtime_lock and build_lock objects are required")
    if runtime.get("path") != RUNTIME_LOCK_PATH.as_posix():
        raise ContainerReleaseError("runtime lock path differs from the Docker build contract")
    if build.get("path") != BUILD_LOCK_PATH.as_posix():
        raise ContainerReleaseError("build lock path differs from the Docker build contract")
    runtime_path = root / str(runtime.get("path", ""))
    build_path = root / str(build.get("path", ""))
    for descriptor, path in ((runtime, runtime_path), (build, build_path)):
        expected_hash = descriptor.get("sha256")
        actual_hash = _sha256_path(path)
        if expected_hash != actual_hash:
            raise ContainerReleaseError(f"{path.name} digest is stale; expected {actual_hash}")

    runtime_pins = _verify_lock(
        runtime_path,
        _direct_names(inputs["runtime_requirements"]),
    )
    build_pins = _verify_lock(build_path, _direct_names(inputs["build_requirements"]))

    base_reference = base.get("reference")
    base_platform = base.get("platform")
    platform_digest = base.get("platform_manifest_digest")
    if (
        not isinstance(base_reference, str)
        or "@sha256:" not in base_reference
        or not _DIGEST.fullmatch(base_reference.rsplit("@", 1)[1])
    ):
        raise ContainerReleaseError("base image must use an exact sha256 reference")
    if base_platform != "linux/amd64" or not isinstance(platform_digest, str):
        raise ContainerReleaseError("base image must bind linux/amd64 and its platform digest")
    if not _DIGEST.fullmatch(platform_digest):
        raise ContainerReleaseError("base image platform manifest digest is invalid")
    if not isinstance(base.get("verified_at"), str) or not re.fullmatch(
        r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", base["verified_at"]
    ):
        raise ContainerReleaseError("base image verification time must be explicit UTC")

    system_packages = policy.get("system_packages")
    if not isinstance(system_packages, dict):
        raise ContainerReleaseError("container lock policy lacks system_packages")
    snapshot = system_packages.get("snapshot")
    repositories = system_packages.get("repositories")
    packages = system_packages.get("packages")
    runtime_versions = system_packages.get("runtime_versions")
    if (
        system_packages.get("provider") != "debian-snapshot"
        or not isinstance(snapshot, str)
        or not re.fullmatch(r"\d{8}T\d{6}Z", snapshot)
    ):
        raise ContainerReleaseError("system packages require an explicit Debian snapshot")
    expected_repositories = [
        f"http://snapshot.debian.org/archive/debian/{snapshot}",
        f"http://snapshot.debian.org/archive/debian-security/{snapshot}",
    ]
    if repositories != expected_repositories:
        raise ContainerReleaseError("system package repositories differ from the snapshot")
    if not isinstance(packages, dict) or set(packages) != {"git"}:
        raise ContainerReleaseError("system packages must contain exactly the required Git pin")
    git_package_version = packages.get("git")
    if not isinstance(git_package_version, str) or not re.fullmatch(
        r"(?=.*\d)[A-Za-z0-9.+:~_-]+", git_package_version
    ):
        raise ContainerReleaseError("Git system package version is not an exact safe pin")
    if not isinstance(runtime_versions, dict) or set(runtime_versions) != {"git"}:
        raise ContainerReleaseError("system runtime versions must bind Git")
    git_runtime_version = runtime_versions.get("git")
    if not isinstance(git_runtime_version, str) or not re.fullmatch(
        r"\d+\.\d+\.\d+", git_runtime_version
    ):
        raise ContainerReleaseError("Git runtime version is invalid")

    dockerfile = (root / "Dockerfile").read_text(encoding="utf-8")
    image_arg = re.search(r"^ARG PYTHON_IMAGE=(\S+)$", dockerfile, re.MULTILINE)
    if image_arg is None or image_arg.group(1) != base_reference:
        raise ContainerReleaseError("Dockerfile base image differs from lock policy")
    expected_args = {
        "DEBIAN_SNAPSHOT": snapshot,
        "GIT_PACKAGE_VERSION": git_package_version,
        "GIT_RUNTIME_VERSION": git_runtime_version,
    }
    for name, expected in expected_args.items():
        match = re.search(rf"^ARG {name}=(\S+)$", dockerfile, re.MULTILINE)
        if match is None or match.group(1) != expected:
            raise ContainerReleaseError(f"Dockerfile {name} differs from lock policy")
    if "python -m samuel" in dockerfile or re.search(
        r'ENTRYPOINT\s+\["python",\s*"-m",\s*"samuel"\]', dockerfile
    ):
        raise ContainerReleaseError("Dockerfile bypasses the installed console entry point")
    for marker in (
        "requirements-container-build.lock",
        "requirements-container.lock",
        "--require-hashes",
        "--no-build-isolation",
        "--no-deps",
        "org.opencontainers.image.base.name",
        'SETUPTOOLS_SCM_PRETEND_VERSION_FOR_SAMUEL="${SAMUEL_VERSION}"',
        'ENTRYPOINT ["samuel"]',
        'SAMUEL_RUNTIME_CONFIG_DIR="/app/config"',
        'CMD samuel --config "${SAMUEL_RUNTIME_CONFIG_DIR}" health',
        "snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT}",
        "snapshot.debian.org/archive/debian-security/${DEBIAN_SNAPSHOT}",
        "Acquire::Check-Valid-Until=false",
        'git="${GIT_PACKAGE_VERSION}"',
        'test "$(git --version)" = "git version ${GIT_RUNTIME_VERSION}"',
    ):
        if marker not in dockerfile:
            raise ContainerReleaseError(f"Dockerfile lacks required marker {marker!r}")
    if 'pip install --no-cache-dir ".[dashboard,llm,github,tree-sitter]"' in dockerfile:
        raise ContainerReleaseError("Dockerfile still resolves open runtime extras")

    dockerignore = (root / ".dockerignore").read_text(encoding="utf-8").splitlines()
    if not dockerignore or dockerignore[0] != "**":
        raise ContainerReleaseError(".dockerignore must remain an allowlist")
    expected_context = {
        "!pyproject.toml",
        "!LICENSE",
        "!requirements-container.lock",
        "!requirements-container-build.lock",
        "!samuel/",
        "!samuel/**",
        "!config/",
        "!config/*.json",
        "!config/llm/",
        "!config/llm/*.json",
        "!config/workflows/",
        "!config/workflows/*.json",
        "config/license.json",
        "config/license.local.json",
    }
    if set(dockerignore[1:]) != expected_context:
        raise ContainerReleaseError(".dockerignore differs from the reviewed context allowlist")

    compose = (root / "docker-compose.yml").read_text(encoding="utf-8")
    for marker in (
        "SAMUEL_IMAGE",
        "SAMUEL_ENV_FILE",
        "SAMUEL_CONFIG_DIR",
        "SAMUEL_DATA_DIR",
        "SAMUEL_DASHBOARD_BIND",
        "SAMUEL_DASHBOARD_PORT",
    ):
        if marker not in compose:
            raise ContainerReleaseError(f"docker-compose.yml lacks {marker}")
    if "/app/.env" in compose:
        raise ContainerReleaseError(
            "docker-compose.yml must not mount the operator env file in production"
        )
    setup_compose = (root / "docker-compose.setup.yml").read_text(encoding="utf-8")
    for marker in (
        "${SAMUEL_ENV_FILE:-.env}:/app/.env:rw",
        "${SAMUEL_CONFIG_DIR:-./config}:/app/config:rw",
        '"--configuration-mode", "setup"',
    ):
        if marker not in setup_compose:
            raise ContainerReleaseError(
                "docker-compose.setup.yml lacks the reviewed setup persistence contract"
            )

    return {
        "base_image": base_reference,
        "base_platform_manifest_digest": platform_digest,
        "runtime_lock_sha256": runtime["sha256"],
        "runtime_packages": len(runtime_pins),
        "build_lock_sha256": build["sha256"],
        "build_packages": len(build_pins),
        "source_digest": expected_source_digest,
        "system_packages_sha256": _sha256_json(system_packages),
        "git_version": git_runtime_version,
    }


def verify_image_inspect(
    inspect: dict[str, Any],
    *,
    version: str,
    commit: str,
    source_url: str,
    base_image: str,
) -> None:
    config = inspect.get("Config")
    if not isinstance(config, dict):
        raise ContainerReleaseError("docker image inspect has no Config object")
    labels = config.get("Labels")
    environment = config.get("Env")
    if not isinstance(labels, dict) or not isinstance(environment, list):
        raise ContainerReleaseError("docker image inspect lacks labels or environment")
    expected_labels = {
        "org.opencontainers.image.version": version,
        "org.opencontainers.image.revision": commit,
        "org.opencontainers.image.source": source_url,
        "org.opencontainers.image.base.name": base_image,
        "org.opencontainers.image.licenses": "Apache-2.0",
    }
    mismatches = {
        name: labels.get(name)
        for name, expected in expected_labels.items()
        if labels.get(name) != expected
    }
    if mismatches:
        raise ContainerReleaseError(f"OCI label mismatch: {mismatches}")
    if f"SAMUEL_BUILD_REVISION={commit}" not in environment:
        raise ContainerReleaseError("image environment does not carry the full build revision")
    if "SAMUEL_RUNTIME_CONFIG_DIR=/app/config" not in environment:
        raise ContainerReleaseError("image does not bind its runtime config directory")
    healthcheck = config.get("Healthcheck")
    expected_healthcheck = [
        "CMD-SHELL",
        'samuel --config "${SAMUEL_RUNTIME_CONFIG_DIR}" health || exit 1',
    ]
    if not isinstance(healthcheck, dict) or healthcheck.get("Test") != expected_healthcheck:
        raise ContainerReleaseError("image healthcheck does not use its runtime config binding")
    if inspect.get("Os") != "linux" or inspect.get("Architecture") != "amd64":
        raise ContainerReleaseError("release image platform must be linux/amd64")


def record_container_manifest(
    manifest_path: Path,
    *,
    tag: str,
    commit: str,
    image_repository: str,
    image_digest: str,
    policy: dict[str, Any],
) -> dict[str, Any]:
    version = product_version_from_tag(tag)
    if version is None:
        raise ContainerReleaseError(f"invalid product tag: {tag!r}")
    if not _FULL_REVISION.fullmatch(commit):
        raise ContainerReleaseError(f"invalid full release commit: {commit!r}")
    if not _DIGEST.fullmatch(image_digest):
        raise ContainerReleaseError(f"invalid image digest: {image_digest!r}")
    if (
        not _IMAGE_REPOSITORY.fullmatch(image_repository)
        or image_repository != image_repository.lower()
    ):
        raise ContainerReleaseError(f"invalid lowercase image repository: {image_repository!r}")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ContainerReleaseError(f"cannot read release manifest: {exc}") from exc
    if not isinstance(manifest, dict):
        raise ContainerReleaseError("release manifest must be a JSON object")
    expected = {"product": "samuel", "tag": tag, "version": version, "commit": commit}
    mismatches = {
        field: manifest.get(field)
        for field, value in expected.items()
        if manifest.get(field) != value
    }
    if mismatches:
        raise ContainerReleaseError(f"release manifest identity mismatch: {mismatches}")
    if not isinstance(manifest.get("artifacts"), list):
        raise ContainerReleaseError("release manifest has no artifacts list")

    base = policy["base_image"]
    contract = policy["lock_contract"]
    manifest["schema_version"] = 2
    manifest["container"] = {
        "image": image_repository,
        "tag": tag,
        "digest": image_digest,
        "reference": f"{image_repository}@{image_digest}",
        "platform": "linux/amd64",
        "base_image": base["reference"],
        "base_platform_manifest_digest": base["platform_manifest_digest"],
        "runtime_lock_sha256": contract["runtime_lock"]["sha256"],
        "system_packages_sha256": _sha256_json(policy["system_packages"]),
        "git_version": policy["system_packages"]["runtime_versions"]["git"],
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    input_text: str | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(  # noqa: S603 - structured operator-selected docker executable
        command,
        cwd=cwd,
        env=env,
        input=input_text,
        check=False,
        capture_output=True,
        text=True,
    )
    if check and completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip() or "command failed"
        raise ContainerReleaseError(f"{' '.join(command)}: {detail}")
    return completed


def _repository_location(image_repository: str) -> tuple[str, str]:
    """Return the explicit registry and personal owner of an OCI repository."""

    parts = image_repository.split("/")
    if len(parts) < 3 or not parts[0] or not parts[1]:
        raise ContainerReleaseError(
            "publisher preflight requires <registry>/<personal-owner>/<image>"
        )
    return parts[0], parts[1]


def _gitea_json(api_url: str, path: str, token: str) -> Any:
    request = Request(
        f"{api_url.rstrip('/')}{path}",
        headers={"Accept": "application/json", "Authorization": f"token {token}"},
    )
    try:
        with urlopen(request, timeout=10) as response:  # noqa: S310 - explicit operator URL
            return json.load(response)
    except HTTPError as exc:
        raise ContainerReleaseError(
            f"publisher API proof failed at {path}: HTTP {exc.code}"
        ) from exc
    except (URLError, TimeoutError, json.JSONDecodeError) as exc:
        raise ContainerReleaseError(f"publisher API proof failed at {path}") from exc


def verify_gitea_publisher(
    *,
    api_url: str,
    image_repository: str,
    publisher_user: str,
    release_host_id: str,
    publisher_token: str,
    runtime_scm_token: str | None,
    allow_insecure: bool,
) -> dict[str, Any]:
    """Verify identity, provider scope, owner access, and credential separation."""

    if (
        not _IMAGE_REPOSITORY.fullmatch(image_repository)
        or image_repository.lower() != image_repository
    ):
        raise ContainerReleaseError(f"invalid lowercase image repository: {image_repository!r}")
    registry, owner = _repository_location(image_repository)
    parsed = urlsplit(api_url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc or parsed.path.rstrip("/"):
        raise ContainerReleaseError("publisher API URL must contain only scheme and authority")
    if parsed.scheme == "http" and not allow_insecure:
        raise ContainerReleaseError("HTTP publisher API requires --registry-insecure")
    if parsed.netloc.lower() != registry.lower():
        raise ContainerReleaseError("publisher API authority differs from the image registry")
    if not _SAFE_ID.fullmatch(publisher_user) or not _SAFE_ID.fullmatch(release_host_id):
        raise ContainerReleaseError("publisher user and release host ID must be safe non-empty IDs")
    if not publisher_token:
        raise ContainerReleaseError(
            f"dedicated publisher credential is missing in {PUBLISHER_TOKEN_ENV}"
        )
    if runtime_scm_token and hmac.compare_digest(publisher_token, runtime_scm_token):
        raise ContainerReleaseError(
            "publisher credential must differ from the runtime SCM credential"
        )

    metadata = _gitea_json(api_url, "/api/v1/token", publisher_token)
    if not isinstance(metadata, dict) or not isinstance(metadata.get("user"), dict):
        raise ContainerReleaseError("publisher token metadata has no bound user identity")
    login = metadata["user"].get("login")
    scopes = metadata.get("scopes")
    if login != publisher_user:
        raise ContainerReleaseError("publisher credential identity differs from --publisher-user")
    if str(login).lower() != owner.lower():
        raise ContainerReleaseError(
            "image owner must be the authenticated personal publisher owner"
        )
    if not isinstance(scopes, list) or not all(isinstance(item, str) for item in scopes):
        raise ContainerReleaseError("publisher token metadata has no readable scope proof")
    scope_set = set(scopes)
    if "write:package" not in scope_set:
        raise ContainerReleaseError("publisher credential does not prove write:package scope")
    extra_write = sorted(
        scope for scope in scope_set if scope.startswith("write:") and scope != "write:package"
    )
    if "all" in scope_set or extra_write:
        raise ContainerReleaseError(
            "publisher credential has broader write scope than package publishing"
        )

    packages = _gitea_json(
        api_url,
        f"/api/v1/packages/{quote(owner, safe='')}?type=container&limit=1",
        publisher_token,
    )
    if not isinstance(packages, list):
        raise ContainerReleaseError("publisher owner package read did not return a package list")

    checked_at = (
        datetime.now(tz=timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    )
    return {
        "schema_version": 1,
        "provider": "gitea",
        "checked_at": checked_at,
        "identity": {"status": "verified", "login": login},
        "credential_separation": {
            "status": "verified",
            "runtime_scm_credential": "different" if runtime_scm_token else "not_present",
        },
        "scope": {
            "status": "verified",
            "granted": sorted(scope_set),
            "technical_boundary": "personal-owner package scope",
            "single_package_isolation": False,
        },
        "owner_read": {"status": "verified", "owner": owner, "package_type": "container"},
        "write_qualification": {
            "status": "verified",
            "basis": "provider token write:package scope plus authenticated personal owner",
            "probe_push": False,
        },
        "organizational_binding": {
            "release_host_id": release_host_id,
            "registry": registry,
            "image_repository": image_repository,
        },
    }


@contextmanager
def _publisher_docker_session(
    *,
    root: Path,
    docker_command: str,
    api_url: str,
    image_repository: str,
    publisher_user: str,
    release_host_id: str,
    registry_insecure: bool,
) -> Iterator[tuple[list[str], dict[str, Any]]]:
    publisher_token = os.getenv(PUBLISHER_TOKEN_ENV, "")
    runtime_scm_token = os.getenv(RUNTIME_SCM_TOKEN_ENV)
    proof = verify_gitea_publisher(
        api_url=api_url,
        image_repository=image_repository,
        publisher_user=publisher_user,
        release_host_id=release_host_id,
        publisher_token=publisher_token,
        runtime_scm_token=runtime_scm_token,
        allow_insecure=registry_insecure,
    )
    docker_base = shlex.split(docker_command)
    if not docker_base:
        raise ContainerReleaseError("docker command must not be empty")
    registry, _owner = _repository_location(image_repository)
    removed = {
        name: os.environ.pop(name)
        for name in (PUBLISHER_TOKEN_ENV, RUNTIME_SCM_TOKEN_ENV)
        if name in os.environ
    }
    try:
        with tempfile.TemporaryDirectory(prefix="samuel-publisher-docker-") as docker_config:
            docker = [*docker_base, "--config", docker_config]
            login = _run(
                [
                    *docker,
                    "login",
                    registry,
                    "--username",
                    publisher_user,
                    "--password-stdin",
                ],
                cwd=root,
                input_text=publisher_token + "\n",
                check=False,
            )
            if login.returncode:
                raise ContainerReleaseError("dedicated publisher registry login failed")
            try:
                yield docker, proof
            finally:
                _run([*docker, "logout", registry], cwd=root, check=False)
    finally:
        os.environ.update(removed)


def _manifest_inspect_command(
    docker: list[str], tagged_image: str, *, registry_insecure: bool
) -> list[str]:
    command = [*docker, "manifest", "inspect"]
    if registry_insecure:
        command.append("--insecure")
    return [*command, tagged_image]


def _prove_tag_absence(
    docker: list[str], tagged_image: str, *, root: Path, registry_insecure: bool
) -> dict[str, str]:
    command = _manifest_inspect_command(docker, tagged_image, registry_insecure=registry_insecure)
    existing = _run(command, cwd=root, check=False)
    if existing.returncode == 0:
        raise ContainerReleaseError(
            f"container tag already exists and is create-only: {tagged_image}"
        )
    missing_detail = (existing.stderr + existing.stdout).lower()
    if not any(
        marker in missing_detail for marker in ("manifest unknown", "no such manifest", "not found")
    ):
        raise ContainerReleaseError("cannot prove container tag absence with publisher credential")
    return {"status": "verified", "image": tagged_image}


def _push_create_only(
    docker: list[str], tagged_image: str, *, root: Path, registry_insecure: bool
) -> None:
    """Push once and fail closed if the transport outcome is ambiguous."""

    pushed = _run([*docker, "push", tagged_image], cwd=root, check=False)
    if pushed.returncode == 0:
        return
    postcondition = _run(
        _manifest_inspect_command(docker, tagged_image, registry_insecure=registry_insecure),
        cwd=root,
        check=False,
    )
    if postcondition.returncode == 0:
        raise ContainerReleaseError(
            "container push reported failure but the create-only tag now exists; "
            "preserve it and reconcile the remote digest without retry or overwrite"
        )
    raise ContainerReleaseError(
        "container push failed and remote outcome is not qualified; do not retry "
        "without reconciling the create-only tag under the same release order"
    )


def publisher_preflight(
    *,
    root: Path,
    image_repository: str,
    tag: str,
    api_url: str,
    publisher_user: str,
    release_host_id: str,
    docker_command: str,
    registry_insecure: bool,
) -> dict[str, Any]:
    if product_version_from_tag(tag) is None:
        raise ContainerReleaseError(f"invalid product tag: {tag!r}")
    tagged_image = f"{image_repository}:{tag}"
    with _publisher_docker_session(
        root=root,
        docker_command=docker_command,
        api_url=api_url,
        image_repository=image_repository,
        publisher_user=publisher_user,
        release_host_id=release_host_id,
        registry_insecure=registry_insecure,
    ) as (docker, proof):
        proof["tag_absence"] = _prove_tag_absence(
            docker, tagged_image, root=root, registry_insecure=registry_insecure
        )
    return proof


def _inspect_image(docker: list[str], image: str, *, root: Path) -> dict[str, Any]:
    output = _run([*docker, "image", "inspect", image], cwd=root).stdout
    try:
        documents = json.loads(output)
    except json.JSONDecodeError as exc:
        raise ContainerReleaseError(f"invalid docker image inspect JSON: {exc}") from exc
    if not isinstance(documents, list) or len(documents) != 1 or not isinstance(documents[0], dict):
        raise ContainerReleaseError("docker image inspect must return exactly one image")
    return documents[0]


def _published_digest(
    docker: list[str], image_repository: str, tagged_image: str, *, root: Path
) -> str:
    """Resolve exactly one immutable repository digest from a pulled tag."""

    inspect = _inspect_image(docker, tagged_image, root=root)
    repo_digests = inspect.get("RepoDigests")
    if not isinstance(repo_digests, list):
        raise ContainerReleaseError("published image has no RepoDigests")
    prefix = f"{image_repository}@"
    candidates = [str(item)[len(prefix) :] for item in repo_digests if str(item).startswith(prefix)]
    if len(candidates) != 1 or not _DIGEST.fullmatch(candidates[0]):
        raise ContainerReleaseError(f"cannot resolve one published digest for {image_repository}")
    return candidates[0]


def _verify_recovery_manifest(manifest_path: Path) -> dict[str, Any]:
    """Reject a manifest that already has a container publication binding."""

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ContainerReleaseError(f"cannot read release manifest: {exc}") from exc
    if not isinstance(manifest, dict):
        raise ContainerReleaseError("release manifest must be a JSON object")
    if manifest.get("schema_version") != 1 or "container" in manifest:
        raise ContainerReleaseError("recovery requires an unrecorded schema-1 release manifest")
    return manifest


def _verify_runtime(
    docker: list[str],
    image: str,
    *,
    root: Path,
    version: str,
    commit: str,
    git_version: str,
) -> None:
    script = (
        "import json,samuel;"
        "print(json.dumps({'version':samuel.__version__,'build':samuel.__build_info__.as_dict()}))"
    )
    completed = _run(
        [*docker, "run", "--rm", "--entrypoint", "python", image, "-c", script],
        cwd=root,
    )
    try:
        evidence = json.loads(completed.stdout.strip())
    except json.JSONDecodeError as exc:
        raise ContainerReleaseError(f"invalid runtime build evidence: {exc}") from exc
    if evidence.get("version") != version:
        raise ContainerReleaseError(
            f"runtime version is {evidence.get('version')!r}, expected {version!r}"
        )
    build = evidence.get("build")
    if not isinstance(build, dict) or build.get("revision") != commit:
        raise ContainerReleaseError("runtime build revision does not match the release commit")
    if build.get("product_version") != version or build.get("revision_source") != "environment":
        raise ContainerReleaseError("runtime build information is not release-bound")

    git_probe = _run(
        [*docker, "run", "--rm", "--entrypoint", "git", image, "--version"],
        cwd=root,
    ).stdout.strip()
    if git_probe != f"git version {git_version}":
        raise ContainerReleaseError(
            f"runtime Git version is {git_probe!r}, expected 'git version {git_version}'"
        )

    absence_script = (
        "test ! -e /app/.env && test ! -e /app/.git && test ! -e /app/tests "
        "&& test ! -e /app/config/license.json && test ! -e /app/config/license.local.json"
    )
    _run(
        [*docker, "run", "--rm", "--entrypoint", "sh", image, "-c", absence_script],
        cwd=root,
    )


def _free_local_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])


def _smoke_compose(
    docker: list[str],
    image: str,
    *,
    root: Path,
    env_file: Path,
    version: str,
    commit: str,
    pull: str = "always",
) -> dict[str, Any]:
    if not env_file.is_file():
        raise ContainerReleaseError(f"compose environment file does not exist: {env_file}")
    if pull not in {"always", "never"}:
        raise ContainerReleaseError(f"unsupported compose pull policy: {pull!r}")
    port = _free_local_port()
    project = f"samuel-release-{commit[:12]}"
    with tempfile.TemporaryDirectory(prefix="samuel-container-smoke-") as temporary:
        temporary_path = Path(temporary)
        data_directory = temporary_path / "data"
        workspace_directory = temporary_path / "workspaces"
        for directory in (data_directory, workspace_directory):
            directory.mkdir(mode=0o777)
            os.chmod(directory, 0o777)
        _run(
            [
                *docker,
                "run",
                "--rm",
                "--user",
                "0:0",
                "--entrypoint",
                "python",
                "--network",
                "none",
                "--volume",
                f"{temporary_path}:/prepare",
                "--mount",
                f"type=bind,src={root / 'tools/container_init.py'},dst=/bootstrap/container_init.py,readonly",
                image,
                "/bootstrap/container_init.py",
                "prepare-smoke",
            ],
            cwd=root,
        )
        compose_variables = temporary_path / "compose.env"
        compose_variables.write_text(
            "\n".join(
                (
                    f"SAMUEL_IMAGE={image}",
                    f"SAMUEL_ENV_FILE={env_file.resolve()}",
                    f"SAMUEL_CONFIG_DIR={(root / 'config').resolve()}",
                    f"SAMUEL_DATA_DIR={data_directory}",
                    f"SAMUEL_WORK_DIR={workspace_directory}",
                    "SAMUEL_DASHBOARD_BIND=127.0.0.1",
                    f"SAMUEL_DASHBOARD_PORT={port}",
                )
            )
            + "\n",
            encoding="utf-8",
        )
        compose = [
            *docker,
            "compose",
            "--env-file",
            str(compose_variables),
            "--project-name",
            project,
            "-f",
            str(root / "docker-compose.yml"),
        ]
        env = os.environ.copy()
        try:
            try:
                _run(
                    [
                        *compose,
                        "up",
                        "-d",
                        "--no-build",
                        "--pull",
                        pull,
                        "--wait",
                        "--wait-timeout",
                        "90",
                    ],
                    cwd=root,
                    env=env,
                )
            except ContainerReleaseError as exc:
                status_text = _run(
                    [*compose, "ps", "--all"], cwd=root, env=env, check=False
                ).stdout.strip()
                logs = _run(
                    [*compose, "logs", "--no-color", "--tail", "100"],
                    cwd=root,
                    env=env,
                    check=False,
                ).stdout.strip()
                raise ContainerReleaseError(
                    f"{exc}; compose status: {status_text or 'unavailable'}; "
                    f"compose logs: {logs or 'unavailable'}"
                ) from exc
            container_id = _run([*compose, "ps", "-q", "samuel"], cwd=root, env=env).stdout.strip()
            if not container_id:
                raise ContainerReleaseError("compose smoke did not start the samuel service")
            inspect = json.loads(
                _run([*docker, "container", "inspect", container_id], cwd=root).stdout
            )[0]
            health = inspect.get("State", {}).get("Health", {}).get("Status")
            if health != "healthy":
                raise ContainerReleaseError(f"compose container health is {health!r}")

            script = (
                "import json,os,urllib.request;"
                "u='http://127.0.0.1:7777/api/v1/dashboard/status';"
                "r=urllib.request.Request(u);"
                "k=os.getenv('SAMUEL_API_KEY','');"
                "r.add_header('Authorization','Bearer '+k) if k else None;"
                "d=json.load(urllib.request.urlopen(r,timeout=5));"
                "print(json.dumps(d['build']))"
            )
            dashboard_status = _run(
                [*compose, "exec", "-T", "samuel", "python", "-c", script],
                cwd=root,
                env=env,
            )
            build = json.loads(dashboard_status.stdout.strip())
            if build.get("product_version") != version or build.get("revision") != commit:
                raise ContainerReleaseError("dashboard build status does not match tag and commit")
            return {"health": health, "dashboard_build": build, "host_port": port}
        finally:
            _run(
                [*compose, "down", "--volumes", "--remove-orphans", "--timeout", "10"],
                cwd=root,
                env=env,
                check=False,
            )
            for directory in (data_directory, workspace_directory):
                _run(
                    [
                        *docker,
                        "run",
                        "--rm",
                        "--entrypoint",
                        "sh",
                        "--volume",
                        f"{directory}:/cleanup",
                        image,
                        "-c",
                        "find /cleanup -mindepth 1 -exec chmod a+rwX {} +",
                    ],
                    cwd=root,
                    check=False,
                )


def publish(
    *,
    root: Path,
    dist_dir: Path,
    tag: str,
    commit_ref: str,
    image_repository: str,
    source_url: str,
    compose_env_file: Path,
    docker_command: str,
    publisher_api_url: str,
    publisher_user: str,
    release_host_id: str,
    registry_insecure: bool = False,
) -> dict[str, Any]:
    contract_evidence = verify_container_contract(root)
    version = product_version_from_tag(tag)
    if version is None:
        raise ContainerReleaseError(f"invalid product tag: {tag!r}")
    manifest_path = run_gate(
        root=root,
        dist_dir=dist_dir,
        tag=tag,
        commit_ref=commit_ref,
        mode="post-tag",
        restore_remote_tag=True,
    )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    commit = str(manifest["commit"])
    local_image = f"samuel-release:{version}-{commit[:12]}"
    tagged_image = f"{image_repository}:{tag}"
    with _publisher_docker_session(
        root=root,
        docker_command=docker_command,
        api_url=publisher_api_url,
        image_repository=image_repository,
        publisher_user=publisher_user,
        release_host_id=release_host_id,
        registry_insecure=registry_insecure,
    ) as (docker, publisher_proof):
        publisher_proof["tag_absence"] = _prove_tag_absence(
            docker, tagged_image, root=root, registry_insecure=registry_insecure
        )

        _run(
            [
                *docker,
                "build",
                "--pull",
                "--no-cache",
                "--platform",
                "linux/amd64",
                "--build-arg",
                f"SAMUEL_VERSION={version}",
                "--build-arg",
                f"SAMUEL_REVISION={commit}",
                "--build-arg",
                f"SAMUEL_SOURCE_URL={source_url}",
                "--tag",
                local_image,
                ".",
            ],
            cwd=root,
        )
        inspect = _inspect_image(docker, local_image, root=root)
        verify_image_inspect(
            inspect,
            version=version,
            commit=commit,
            source_url=source_url,
            base_image=contract_evidence["base_image"],
        )
        _verify_runtime(
            docker,
            local_image,
            root=root,
            version=version,
            commit=commit,
            git_version=str(contract_evidence["git_version"]),
        )

        _run([*docker, "tag", local_image, tagged_image], cwd=root)
        _push_create_only(docker, tagged_image, root=root, registry_insecure=registry_insecure)

        image_digest = _published_digest(docker, image_repository, tagged_image, root=root)
        digest_reference = f"{image_repository}@{image_digest}"

        smoke = _smoke_compose(
            docker,
            digest_reference,
            root=root,
            env_file=compose_env_file,
            version=version,
            commit=commit,
        )
        policy = load_policy(root)
        recorded = record_container_manifest(
            manifest_path,
            tag=tag,
            commit=commit,
            image_repository=image_repository,
            image_digest=image_digest,
            policy=policy,
        )
        publisher_proof["publish_postcondition"] = {
            "status": "verified",
            "digest_reference": digest_reference,
        }
        return {
            "tag": tag,
            "version": version,
            "commit": commit,
            "image": tagged_image,
            "digest_reference": digest_reference,
            "manifest": str(manifest_path),
            "manifest_schema": recorded["schema_version"],
            "publisher": publisher_proof,
            "contract": contract_evidence,
            "smoke": smoke,
        }


def recover(
    *,
    root: Path,
    dist_dir: Path,
    tag: str,
    commit_ref: str,
    image_repository: str,
    source_url: str,
    compose_env_file: Path,
    docker_command: str,
    publisher_api_url: str,
    publisher_user: str,
    release_host_id: str,
    registry_insecure: bool = False,
) -> dict[str, Any]:
    """Recover only an interrupted post-push, pre-manifest container release.

    This path has no build, tag, push, retag, delete, or Gitea-release action.
    It records a manifest only after a freshly pulled existing image passes
    identity, runtime, and digest-bound Compose smoke verification.
    """

    contract_evidence = verify_container_contract(root)
    version = product_version_from_tag(tag)
    if version is None:
        raise ContainerReleaseError(f"invalid product tag: {tag!r}")
    manifest_path = run_gate(
        root=root,
        dist_dir=dist_dir,
        tag=tag,
        commit_ref=commit_ref,
        mode="post-tag",
        restore_remote_tag=True,
    )
    manifest = _verify_recovery_manifest(manifest_path)
    commit = str(manifest.get("commit", ""))
    tagged_image = f"{image_repository}:{tag}"
    with _publisher_docker_session(
        root=root,
        docker_command=docker_command,
        api_url=publisher_api_url,
        image_repository=image_repository,
        publisher_user=publisher_user,
        release_host_id=release_host_id,
        registry_insecure=registry_insecure,
    ) as (docker, publisher_proof):
        existing = _run(
            _manifest_inspect_command(docker, tagged_image, registry_insecure=registry_insecure),
            cwd=root,
            check=False,
        )
        if existing.returncode != 0:
            raise ContainerReleaseError(
                "recovery requires one already published create-only container tag"
            )
        _run([*docker, "pull", "--platform", "linux/amd64", tagged_image], cwd=root)
        image_digest = _published_digest(docker, image_repository, tagged_image, root=root)
        digest_reference = f"{image_repository}@{image_digest}"
        inspect = _inspect_image(docker, digest_reference, root=root)
        verify_image_inspect(
            inspect,
            version=version,
            commit=commit,
            source_url=source_url,
            base_image=contract_evidence["base_image"],
        )
        _verify_runtime(
            docker,
            digest_reference,
            root=root,
            version=version,
            commit=commit,
            git_version=str(contract_evidence["git_version"]),
        )
        smoke = _smoke_compose(
            docker,
            digest_reference,
            root=root,
            env_file=compose_env_file,
            version=version,
            commit=commit,
        )
        recorded = record_container_manifest(
            manifest_path,
            tag=tag,
            commit=commit,
            image_repository=image_repository,
            image_digest=image_digest,
            policy=load_policy(root),
        )
    return {
        "tag": tag,
        "version": version,
        "commit": commit,
        "digest_reference": digest_reference,
        "manifest": str(manifest_path),
        "manifest_schema": recorded["schema_version"],
        "recovery": {"status": "verified", "mutations": "none"},
        "publisher": publisher_proof,
        "contract": contract_evidence,
        "smoke": smoke,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("check", help="verify the offline container build/lock contract")

    record_parser = subparsers.add_parser("record", help="add a verified digest to a manifest")
    record_parser.add_argument("--manifest", type=Path, required=True)
    record_parser.add_argument("--tag", required=True)
    record_parser.add_argument("--commit", required=True)
    record_parser.add_argument("--image-repository", required=True)
    record_parser.add_argument("--image-digest", required=True)

    preflight_parser = subparsers.add_parser(
        "preflight", help="verify the dedicated Gitea publisher without publishing"
    )
    preflight_parser.add_argument("--root", type=Path, default=ROOT)
    preflight_parser.add_argument("--tag", required=True)
    preflight_parser.add_argument("--image-repository", required=True)
    preflight_parser.add_argument("--publisher-api-url", required=True)
    preflight_parser.add_argument("--publisher-user", required=True)
    preflight_parser.add_argument("--release-host-id", required=True)
    preflight_parser.add_argument("--docker-command", default="docker")
    preflight_parser.add_argument(
        "--registry-insecure",
        action="store_true",
        help="allow an explicitly HTTP Gitea API and registry preflight",
    )

    publish_parser = subparsers.add_parser("publish", help="build, push, smoke, and record")
    publish_parser.add_argument("--root", type=Path, default=ROOT)
    publish_parser.add_argument("--dist-dir", type=Path, required=True)
    publish_parser.add_argument("--tag", required=True)
    publish_parser.add_argument("--commit-ref", default="origin/main")
    publish_parser.add_argument("--image-repository", required=True)
    publish_parser.add_argument("--source-url", required=True)
    publish_parser.add_argument("--compose-env-file", type=Path, required=True)
    publish_parser.add_argument("--docker-command", default="docker")
    publish_parser.add_argument("--publisher-api-url", required=True)
    publish_parser.add_argument("--publisher-user", required=True)
    publish_parser.add_argument("--release-host-id", required=True)
    publish_parser.add_argument(
        "--registry-insecure",
        action="store_true",
        help="allow the create-only preflight against an explicitly HTTP registry",
    )

    recover_parser = subparsers.add_parser(
        "recover", help="verify an interrupted post-push release without publishing"
    )
    recover_parser.add_argument("--root", type=Path, default=ROOT)
    recover_parser.add_argument("--dist-dir", type=Path, required=True)
    recover_parser.add_argument("--tag", required=True)
    recover_parser.add_argument("--commit-ref", default="origin/main")
    recover_parser.add_argument("--image-repository", required=True)
    recover_parser.add_argument("--source-url", required=True)
    recover_parser.add_argument("--compose-env-file", type=Path, required=True)
    recover_parser.add_argument("--docker-command", default="docker")
    recover_parser.add_argument("--publisher-api-url", required=True)
    recover_parser.add_argument("--publisher-user", required=True)
    recover_parser.add_argument("--release-host-id", required=True)
    recover_parser.add_argument("--registry-insecure", action="store_true")
    args = parser.parse_args()

    try:
        if args.command == "check":
            evidence = verify_container_contract(ROOT)
        elif args.command == "record":
            evidence = record_container_manifest(
                args.manifest,
                tag=args.tag,
                commit=args.commit,
                image_repository=args.image_repository,
                image_digest=args.image_digest,
                policy=load_policy(ROOT),
            )
        elif args.command == "preflight":
            evidence = publisher_preflight(
                root=args.root.resolve(),
                image_repository=args.image_repository,
                tag=args.tag,
                api_url=args.publisher_api_url,
                publisher_user=args.publisher_user,
                release_host_id=args.release_host_id,
                docker_command=args.docker_command,
                registry_insecure=args.registry_insecure,
            )
        elif args.command == "publish":
            evidence = publish(
                root=args.root.resolve(),
                dist_dir=args.dist_dir.resolve(),
                tag=args.tag,
                commit_ref=args.commit_ref,
                image_repository=args.image_repository,
                source_url=args.source_url,
                compose_env_file=args.compose_env_file.resolve(),
                docker_command=args.docker_command,
                publisher_api_url=args.publisher_api_url,
                publisher_user=args.publisher_user,
                release_host_id=args.release_host_id,
                registry_insecure=args.registry_insecure,
            )
        else:
            evidence = recover(
                root=args.root.resolve(),
                dist_dir=args.dist_dir.resolve(),
                tag=args.tag,
                commit_ref=args.commit_ref,
                image_repository=args.image_repository,
                source_url=args.source_url,
                compose_env_file=args.compose_env_file.resolve(),
                docker_command=args.docker_command,
                publisher_api_url=args.publisher_api_url,
                publisher_user=args.publisher_user,
                release_host_id=args.release_host_id,
                registry_insecure=args.registry_insecure,
            )
    except (ContainerReleaseError, OSError, subprocess.SubprocessError, ValueError) as exc:
        print(f"container release failed: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(evidence, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
